# Use postgres/example user/password credentials
version: '3.2'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    networks:
      - postgres
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  centos:
    image: centos
    networks:
      - postgres
networks:
  postgres:
    driver: bridge
