# Use postgres/example user/password credentials
version: '3.2'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    networks:
      - postgres
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  centos:
    image: centos
    build:
      context: ./loading_stage
      dockerfile: Dockerfile
    networks:
      - postgres
    depends_on:
      - db
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; python /app/src/insert_data_into_postgres.py'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_SERVICE_NAME=${POSTGRES_SERVICE_NAME}
      - POSTGRES_DB=${POSTGRES_DB}
      - TABLE_NAME=${TABLE_NAME}
      - POSTGRES_DEFAULT_SCHEMA=${POSTGRES_DEFAULT_SCHEMA}
      - POSTGRES_PORT=${POSTGRES_PORT}
  pythonapp:
    container_name: pythonapp
    image: pythonapp
    build:
      context: ./rest_api
      dockerfile: Dockerfile
    networks:
      - postgres
    depends_on:
      - db
    ports:
      - "80:80"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; flask run --host=0.0.0.0 --port=80'
networks:
  postgres:
    driver: bridge
