# Use postgres/example user/password credentials
version: '3.2'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    networks:
      - postgres
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  centos:
    image: centos
    build:
      context: .
      dockerfile: Dockerfile.centos
    networks:
      - postgres
    depends_on:
      - db
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; python /app/src/insert_data_into_postgres.py'
  pythonapp:
    container_name: pythonapp
    image: pythonapp
    build:
      context: ./rest_api
      dockerfile: Dockerfile
    networks:
      - postgres
    depends_on:
      - db
    ports:
      - "80:80"
    environment:
      - DATABASE_URL=postgresql://root:password@db:5432/postgres
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; flask run --host=0.0.0.0 --port=80'
networks:
  postgres:
    driver: bridge
